server:
  port: 8080
  instance:
    instance-id: ${spring.application.name}:${instance-id:${random.value}}

spring:
  application:
    name: url-shortener-service
  main:
    allow-bean-definition-overriding: true

  logging:
    level:
      org:
        springframework:
          data:
            mongodb:
              core:
                MongoTemplate: DEBUG

  data:
    mongodb:
      database: url_shortener
      #authentication-database: admin
      host: localhost
      port: 27017
      #username: acm
      #password: 123
      repositories:
        enabled: true

redis:
  db-url: localhost
  port: 6379

spring-doc:
  version: 1.0

base:
  url: http://localhost

retention:
  period:
    days: 2

logging:
  level:
    ROOT: INFO

token:
  secret: jguy5675hghgtrljkh